import type { NextPage } from "next";
import Head from "next/head";
import { ChevronLeft, ChevronRight } from "react-feather";
import { BlogCard, HeroCard, HorizontalCard } from "../components/card";
import Footer from "../components/footer";
import { RightArrow } from "../components/icons";

const description =
  "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vero ex ad aliquid? Temporibus vitae totam sapiente numquam nihil illum pariatur sequi veritatis, culpa quisquam, dicta possimus ex consequatur non voluptatem.";

const blogs = [
  {
    title: "Universe Unchained",
    author: "Amy Adams",
    imgUrl: "https://picsum.photos/200/200",
    description: description,
  },
  {
    title: "Death Valley",
    author: "Kaley Cuoco",
    imgUrl: "https://picsum.photos/201/200",
    description: description,
  },
  {
    title: "Its All Matter",
    author: "Shiv Raj",
    imgUrl: "https://picsum.photos/200/201",
    description: description,
  },
  {
    title: "Patent Practice",
    author: "Rahul Jassal",
    imgUrl: "https://picsum.photos/202/200",
    description: description,
  },
  {
    title: "Mega Machines",
    author: "Kumar Nayan",
    imgUrl: "https://picsum.photos/200/202",
    description: description,
  },
  {
    title: "Steel City",
    author: "Avi Shekhar",
    imgUrl: "https://picsum.photos/201/201",
    description: description,
  },
  {
    title: "Rate Movies",
    author: "Pankaj Sir",
    imgUrl: "https://picsum.photos/201/201",
    description: description,
  },
  {
    title: "Let's Auction",
    author: "James Bay",
    imgUrl: "https://picsum.photos/203/200",
    description: description,
  },
];

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="hero flex flex-col justify-end pb-2">
        <div className="mt-24"></div>
        <div className="flex justify-start">
          <div className="lg:w-48 px-0"></div>
          <HeroCard
            category="Technology"
            title="It all Starts Here"
            description={description}
            author="Amy Winehouse"
          />
        </div>
        <div className="mt-24"></div>
        <div className="flex items-center justify-center">
          <div className="w-48 text-white text-center flex items-center justify-center">
            <ChevronLeft className="mr-2 cursor-pointer" /> 1 / 5
            <ChevronRight className="ml-2 cursor-pointer" />
          </div>
        </div>

      </div>
      <div className="mt-24"></div>

      <div className="pb-10 lg:px-48 px-4">
        <h4 className="text-3xl">Most Read</h4>
        <HorizontalCard
          title="Universe Unchained"
          description={description}
          author="Amy Winehouse"
          imgUrl="https://picsum.photos/600/400"
        />
        <HorizontalCard
          title="Silicon Valley"
          description={description}
          author="Peter Hendricks"
          imgUrl="https://picsum.photos/650/400"
        />
      </div>

      <div className="lg:px-48 px-4 py-20 bg-gray-50">
        <h4 className="text-3xl mb-6">Most Recent</h4>
        <div className="grid lg:grid-cols-3 md:grid-cols-2 sm:grid-cols-1 gap-10 mb-8">
          {blogs.map((blog, index) => (
            <BlogCard
              key={index}
              title={blog.title}
              author={blog.author}
              description={blog.description}
              imgUrl={blog.imgUrl}
            />
          ))}
        </div>
        <div className="flex items-center justify-center">
          <button className="p-2 px-4 flex items-center bg-black ">
            <p className="mr-4 text-white">Load More</p>
            <RightArrow color="white" width="20px" />
          </button>
        </div>
      </div>

      <div className="bg-black py-20 w-full text-center">
        <h4 className="text-white text-2xl mb-4">
          Subscribe and never miss any updates
        </h4>
        <div className="flex lg:flex-row md:flex-row flex-col justify-center">
          <input
            className="lg:w-80 w-full h-10 mb-2 outline-none invalid:border-red-500 px-4"
            type="email"
            placeholder="john.doe@email.com"
          />
          <button className="bg-white mb-2 h-10 px-4 flex items-center lg:justify-start justify-center">
            <h4 className="text-lg mr-4">Subscribe</h4>
            <RightArrow color="black" width="20px" />
          </button>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default Home;
